version: '3'

services:
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn:latest
    privileged: true
    restart: always
    ports:
      - 9091:9091
    environment:
      - PUID=1000
      - PGID=1000
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
      - LOCAL_NETWORK=${LOCAL_NETWORK}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MOUNT_POINT}/transmission:/data

  radarr:
    container_name: radarr
    image: aront/radarr:latest
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MOUNT_POINT}/radarr-config:/config
      - ${MOUNT_POINT}/transmission:/downloads
      - ${MOUNT_POINT}/mp4_automator:/config_mp4_automator
      - ${MOUNT_POINT}/plex/movies:/movies
    depends_on:
      - transmission
  
  sonarr:
    container_name: sonarr
    image: aront/sonarr:latest
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MOUNT_POINT}/sonarr/config:/config
      - ${MOUNT_POINT}/transmission:/downloads
      - ${MOUNT_POINT}/mp4_automator:/config_mp4_automator
      - ${MOUNT_POINT}/plex/tv:/tv
    depends_on:
      - transmission
  
  jackett:
    container_name: jackett
    image: linuxserver/jackett:latest
    ports:
      - 9117:9117
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - ${MOUNT_POINT}/jackett/config/:/config
      - ${MOUNT_POINT}/jackett/downloads/:/downloads

  plex:
    container_name: plex
    image: plexinc/pms-docker:latest
    ports:
     - 32400:32400
     - 1900:1900/udp
     - 3005:3005
     - 5353:5353/udp
     - 8324:8324
     - 32410:32410/udp
     - 32412:32412/udp
     - 32413:32413/udp
     - 32414:32414/udp
     - 32469:32469
    restart: always
    network_mode: host
    volumes:
      - ${MOUNT_POINT}/plex-config/:/config
      - ${MOUNT_POINT}/plex/:/data
